/**
 * World Story — Balance Agent
 * =========================
 * Manages dynamic world state generation via LLM.
 * Generates and updates country data (population, GDP, military, ideology, allies, enemies).
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { LLMRouter } from '../llm';
import { getCountry, type Country } from '../utils/countries';
import { parseJsonLoose } from '../utils/json-repair';

export interface CountryState {
  code: string;           // USA, RUS, CHN, etc.
  name: string;           // United States, Russia, etc.
  color: string;          // Country color

  // Generated by LLM
  population?: number;     // ~150_000_000
  gdp?: number;          // GDP index (relative)
  military?: number;      // Military index (relative)
  ideology?: string;      // "democracy", "communism", etc.
  allies?: string[];      // ["GBR", "FRA", "DEU"]
  enemies?: string[];     // ["USSR"]

  // Status
  status?: 'superpower' | 'major' | 'regional' | 'minor';
}

export interface WorldState {
  date: string;
  countries: Map<string, CountryState>;
}

/** M01 passo 4: modalità di catalogo e impronta di contenuto (MAT18). */
export interface SimulationGenerationOptions {
  /** strict = nessun bilanciamento di alleanze/potenze non autorizzato. */
  mode?: 'strict' | 'authored';
  /** Impronta di contenuto del catalogo simulation/; null per i mondi legacy. */
  catalogFingerprint?: string | null;
}

export class BalanceAgent {
  private provider: LLMRouter;
  // Una risposta LLM contiene più paesi: da 112 chiamate separate passiamo
  // normalmente a 7 blocchi, elaborati con concorrenza limitata.
  private readonly COUNTRIES_PER_REQUEST = 16;
  private readonly REQUEST_CONCURRENCY = 3;
  private readonly CACHE_VERSION = 3;

  constructor(provider: LLMRouter) {
    this.provider = provider;
  }

  /**
   * Generate initial state for all countries in a template
   * Uses parallel batch processing for speed (~2-3 min instead of 11+ min)
   */
  async generateInitialWorldState(
    template: {
      id: string;
      name: string;
      country_codes: string[];
      base_prompt: string;
      start_date: string;
    },
    countriesOverride?: { code: string; name: string; color: string }[],
    onProgress?: (done: number, total: number) => void,
    options?: SimulationGenerationOptions
  ): Promise<WorldState> {
    console.log('[BalanceAgent] Generating initial world state for template:', template.name);
    // M01 passo 4: la modalità del catalogo decide il bilanciamento; l'impronta
    // di contenuto separa le cache fra regole diverse (MAT18).
    const mode = options?.mode ?? 'authored';
    const fingerprint = options?.catalogFingerprint ?? null;

    const countries = new Map<string, CountryState>();

    // Этап 5: у пресет-пакета могут быть свои страны (имена/цвета) —
    // тогда доверяем пресету и не фильтруем через data/countries.json.
    // Иначе — прежнее поведение: только коды, известные реестру.
    const validCountries: Country[] = countriesOverride && countriesOverride.length > 0
      ? countriesOverride.map(c => ({ code: c.code, name: c.name, color: c.color }))
      : template.country_codes
          .map(code => getCountry(code))
          .filter((c): c is Country => c !== null && c !== undefined);

    const total = validCountries.length;
    onProgress?.(0, total);

    // 1) Cache per contenuto del preset E del catalogo: le nuove partite
    // successive sono immediate; due preset con lo stesso anno ma regole
    // diverse NON condividono la cache (MAT18).
    const cached = this.loadCache(template, validCountries, fingerprint);
    if (cached) {
      onProgress?.(total, total);
      console.log('[BalanceAgent] Cache hit:', total, 'countries');
      return { date: template.start_date, countries: cached };
    }

    // 2) Riusa statistiche di un mondo già generato. Con un catalogo dichiarato
    // l'accesso è consentito SOLO a mondi generati con la STESSA impronta:
    // un clone nello stesso anno con regole diverse non riusa il baseline.
    const reused = await this.reuseExistingWorld(template, validCountries, fingerprint);
    if (reused) {
      onProgress?.(total, total);
      this.saveCache(template, validCountries, reused, fingerprint);
      console.log('[BalanceAgent] Reused an existing world:', total, 'countries');
      return { date: template.start_date, countries: reused };
    }

    // 3) Primo avvio assoluto: blocchi da 16 paesi, tre richieste concorrenti.
    // Il vecchio percorso faceva una chiamata per ciascuna nazione.
    const batches: Country[][] = [];
    for (let i = 0; i < validCountries.length; i += this.COUNTRIES_PER_REQUEST) {
      batches.push(validCountries.slice(i, i + this.COUNTRIES_PER_REQUEST));
    }
    let done = 0;
    for (let i = 0; i < batches.length; i += this.REQUEST_CONCURRENCY) {
      const wave = batches.slice(i, i + this.REQUEST_CONCURRENCY);
      const results = await Promise.all(wave.map(batch =>
        this.generateCountryBatch(batch, template.start_date, template.base_prompt)
      ));
      for (const states of results) {
        for (const state of states) countries.set(state.code, state);
        done += states.length;
        onProgress?.(Math.min(done, total), total);
      }
    }

    await this.balanceWorld(countries, mode);
    this.saveCache(template, validCountries, countries, fingerprint);
    onProgress?.(total, total);

    console.log('[BalanceAgent] World generation complete:', countries.size, 'countries');
    return {
      date: template.start_date,
      countries,
    };
  }

  private cacheFile(
    template: { id: string; start_date: string; base_prompt: string },
    countries: Country[],
    fingerprint: string | null,
  ): string {
    const key = crypto.createHash('sha256').update(JSON.stringify({
      version: this.CACHE_VERSION,
      id: template.id,
      date: template.start_date,
      prompt: template.base_prompt,
      countries: countries.map(c => [c.code, c.name, c.color]),
      // M01 passo 4 (MAT18): l'impronta di contenuto del catalogo entra
      // nella chiave — stesso anno, regole diverse → file di cache diverso.
      catalog: fingerprint,
    })).digest('hex').slice(0, 20);
    return path.join(process.cwd(), '.cache', 'balance', `${key}.json`);
  }

  private loadCache(
    template: { id: string; start_date: string; base_prompt: string },
    countries: Country[],
    fingerprint: string | null,
  ): Map<string, CountryState> | null {
    try {
      const file = this.cacheFile(template, countries, fingerprint);
      if (!fs.existsSync(file)) return null;
      const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
      // Difesa: la cache porta l'impronta con cui è stata scritta.
      if ((raw?.catalogFingerprint ?? null) !== fingerprint) return null;
      const list = Array.isArray(raw?.countries) ? raw.countries : [];
      const map = new Map<string, CountryState>(list.map((state: CountryState) => [state.code, state]));
      return countries.every(c => map.has(c.code)) ? map : null;
    } catch (e) {
      console.warn('[BalanceAgent] Cache non leggibile:', e);
      return null;
    }
  }

  private saveCache(
    template: { id: string; start_date: string; base_prompt: string },
    countries: Country[],
    states: Map<string, CountryState>,
    fingerprint: string | null,
  ): void {
    try {
      const file = this.cacheFile(template, countries, fingerprint);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      const tmp = `${file}.tmp-${process.pid}`;
      fs.writeFileSync(tmp, JSON.stringify({ version: this.CACHE_VERSION, catalogFingerprint: fingerprint, countries: [...states.values()] }));
      fs.renameSync(tmp, file);
    } catch (e) {
      console.warn('[BalanceAgent] Cache non scritta:', e);
    }
  }

  /**
   * Recupera statistiche già calcolate da un mondo con stessa data e stessi
   * paesi. Il codice geografico originario (`flag`) resta stabile anche dopo
   * conquiste, quindi mondi nazionali e provinciali sono intercambiabili.
   */
  private async reuseExistingWorld(
    template: { name: string; start_date: string },
    countries: Country[],
    fingerprint: string | null,
  ): Promise<Map<string, CountryState> | null> {
    try {
      const db = (await import('../database')).default;
      // M01 passo 4 (MAT18): mondi con catalogo sono riusabili solo da
      // template con la STESSA impronta; template legacy (senza catalogo)
      // riusano solo mondi legacy (fingerprint NULL).
      const candidates = db.prepare(`
        SELECT id, name FROM worlds
        WHERE start_date = ?
          AND COALESCE(catalog_fingerprint, '') = COALESCE(?, '')
        ORDER BY CASE WHEN name LIKE ? THEN 0 ELSE 1 END, created_at DESC
        LIMIT 30
      `).all(template.start_date, fingerprint, `${template.name} -%`) as { id: string; name: string }[];
      const required = new Set(countries.map(c => c.code));

      for (const candidate of candidates) {
        const rows = db.prepare(`
          SELECT COALESCE(NULLIF(flag, ''), owner) AS code,
                 SUM(population) AS population, SUM(gdp) AS gdp,
                 SUM(military_power) AS military
          FROM world_regions WHERE world_id = ?
          GROUP BY COALESCE(NULLIF(flag, ''), owner)
        `).all(candidate.id) as { code: string; population: number; gdp: number; military: number }[];
        const stats = new Map(rows.map(row => [row.code, row]));
        const covered = [...required].filter(code => stats.has(code)).length;
        // Alcuni preset storici includono una politia senza geometria nel
        // GeoJSON (es. YUG): basta una copertura quasi completa.
        if (covered / Math.max(1, required.size) < 0.9) continue;

        const relations = db.prepare(`
          SELECT from_region_id AS fromCode, to_region_id AS toCode, relationship
          FROM country_relationships WHERE world_id = ?
        `).all(candidate.id) as { fromCode: string; toCode: string; relationship: string }[];
        const allies = new Map<string, string[]>();
        const enemies = new Map<string, string[]>();
        for (const rel of relations) {
          const target = rel.relationship === 'ally' ? allies : rel.relationship === 'hostile' ? enemies : null;
          if (target && required.has(rel.fromCode) && required.has(rel.toCode)) {
            (target.get(rel.fromCode) || (target.set(rel.fromCode, []), target.get(rel.fromCode)!)).push(rel.toCode);
          }
        }

        const result = new Map<string, CountryState>();
        for (const country of countries) {
          const row = stats.get(country.code);
          if (!row) {
            result.set(country.code, this.defaultState(country));
            continue;
          }
          const military = Math.max(1, Math.round(Number(row.military) || 1));
          const gdp = Math.max(1, Math.round(Number(row.gdp) || 1));
          result.set(country.code, {
            code: country.code,
            name: country.name,
            color: country.color,
            population: Math.max(100_000, Math.round(Number(row.population) || 10_000_000)),
            gdp,
            military,
            ideology: this.inferIdeology(country.code, template.start_date),
            allies: allies.get(country.code) || [],
            enemies: enemies.get(country.code) || [],
            status: military >= 85 || gdp >= 85 ? 'superpower'
              : military >= 45 || gdp >= 45 ? 'major'
              : military >= 15 || gdp >= 15 ? 'regional' : 'minor',
          });
        }
        return result;
      }
    } catch (e) {
      console.warn('[BalanceAgent] Riuso di un mondo precedente non disponibile:', e);
    }
    return null;
  }

  private inferIdeology(code: string, date: string): string {
    const year = Number(date.slice(0, 4));
    const communist = year < 1992
      ? new Set(['USSR', 'RUS', 'CHN', 'PRK', 'CUB', 'VNM', 'LAO', 'POL', 'CZE', 'SVK', 'HUN', 'ROU', 'BGR', 'DDR', 'YUG'])
      : new Set(['CHN', 'PRK', 'CUB', 'VNM', 'LAO']);
    if (communist.has(code)) return 'comunismo';
    const monarchies = new Set(['GBR', 'ESP', 'SWE', 'NOR', 'DNK', 'NLD', 'BEL', 'JPN', 'SAU', 'JOR', 'MAR', 'THA']);
    return monarchies.has(code) ? 'monarchia costituzionale' : 'repubblica';
  }

  private defaultState(country: Country): CountryState {
    return {
      code: country.code, name: country.name, color: country.color,
      population: 10_000_000, gdp: 10, military: 10,
      ideology: 'neutral', allies: [], enemies: [], status: 'minor',
    };
  }

  /** Genera fino a 16 nazioni in una singola risposta JSON. */
  private async generateCountryBatch(countries: Country[], date: string, worldPrompt: string): Promise<CountryState[]> {
    const system = `Genera dati geopolitici realistici. Rispondi SOLO con JSON valido nel formato
{"countries":{"COD":{"population":numero,"gdp":numero,"military":numero,"ideology":"stringa","allies":[],"enemies":[],"status":"superpower|major|regional|minor"}}}.
GDP e military sono indici relativi agli USA=100. Usa esclusivamente i codici forniti.`;
    const user = `Data: ${date}\nScenario: ${worldPrompt}\nNazioni:\n${countries.map(c => `${c.code}: ${c.name}`).join('\n')}`;
    try {
      const response = await this.provider.generate('balance', system, user, { temperature: 0.35, jsonMode: true });
      const parsed = parseJsonLoose<any>(response.content);
      const rawCountries = parsed?.countries && typeof parsed.countries === 'object' ? parsed.countries : parsed;
      return countries.map(country => {
        const raw = rawCountries?.[country.code];
        if (!raw || typeof raw !== 'object') return this.defaultState(country);
        const status = ['superpower', 'major', 'regional', 'minor'].includes(raw.status) ? raw.status : 'minor';
        return {
          code: country.code, name: country.name, color: country.color,
          population: Math.max(100_000, Number(raw.population) || 10_000_000),
          gdp: Math.max(1, Number(raw.gdp) || 10),
          military: Math.max(1, Number(raw.military) || 10),
          ideology: String(raw.ideology || 'neutral'),
          allies: Array.isArray(raw.allies) ? raw.allies.map(String) : [],
          enemies: Array.isArray(raw.enemies) ? raw.enemies.map(String) : [],
          status,
        };
      });
    } catch (e) {
      console.error('[BalanceAgent] Batch generation failed, uso valori base:', e);
      return countries.map(country => this.defaultState(country));
    }
  }

  /**
   * Generate state for a single country via LLM (compatibilità/API interna).
   */
  async generateCountryState(
    country: Country,
    date: string,
    worldPrompt: string
  ): Promise<CountryState> {
    const system = `Sei un generatore di dati realistici per una nazione in una storia alternativa.

Il tuo compito è generare lo stato iniziale della nazione partendo da dati storici reali.

Regole:
1. Population — popolazione reale nell'anno indicato
2. GDP — indice relativo agli USA = 100
3. Military — indice di potenza militare relativo agli USA = 100
4. Ideology — ideologia politica della nazione, in italiano (es. "democrazia", "comunismo", "monarchia")
5. Allies — codici delle nazioni alleate (alleanze reali del periodo)
6. Enemies — codici delle nazioni nemiche (contrasti reali)
7. Status — 'superpower', 'major', 'regional' o 'minor'

Formato della risposta — SOLO JSON:
{
  "population": numero,
  "gdp": numero,
  "military": numero,
  "ideology": "stringa",
  "allies": ["COD1", "COD2"],
  "enemies": ["COD1", "COD2"],
  "status": "superpower|major|regional|minor"
}`;

    const user = `Nazione: ${country.name} (${country.code})
Data: ${date}
Mondo: ${worldPrompt}

Genera uno stato iniziale realistico per questa nazione.`;

    try {
      const result = await this.provider.generate('balance', system, user, { temperature: 0.7 });

      // Strip markdown code fences if present
      let jsonContent = result.content.trim();
      if (jsonContent.startsWith('```json')) {
        jsonContent = jsonContent.slice(7);
      } else if (jsonContent.startsWith('```')) {
        jsonContent = jsonContent.slice(3);
      }
      if (jsonContent.endsWith('```')) {
        jsonContent = jsonContent.slice(0, -3);
      }
      jsonContent = jsonContent.trim();

      let parsed = JSON.parse(jsonContent);

      // Ensure arrays and strings
      return {
        code: country.code,
        name: country.name,
        color: country.color,
        population: parsed.population || 10_000_000,
        gdp: parsed.gdp || 50,
        military: parsed.military || 50,
        ideology: parsed.ideology || "neutral",
        allies: parsed.allies || [],
        enemies: parsed.enemies || [],
        status: parsed.status || "regional",
      };
    } catch (e) {
      console.error('[BalanceAgent] Failed to generate state for', country.code, e);
      // Return default state
      return {
        code: country.code,
        name: country.name,
        color: country.color,
        population: 10_000_000,
        gdp: 50,
        military: 50,
        ideology: "neutral",
        allies: [],
        enemies: [],
        status: "regional",
      };
    }
  }

  /**
   * Balance the world — no country should be too dominant
   */
  async balanceWorld(countries: Map<string, CountryState>, mode: 'strict' | 'authored' = 'authored'): Promise<void> {
    // M01 passo 4: nella modalità rigorosa il bilanciamento di alleanze e
    // potenze NON è autorizzato — lo storico con stime dichiarate non viene
    // riequilibrato a posteriori. Solo la modalità d'autore può riequilibrare.
    if (mode === 'strict') return;

    // Find superpower(s)
    const superpowers = Array.from(countries.values()).filter(c => c.status === 'superpower');

    if (superpowers.length > 2) {
      // Too many superpowers — demote some
      for (let i = 2; i < superpowers.length; i++) {
        superpowers[i].status = 'major';
        superpowers[i].military = Math.floor((superpowers[i].military || 100) * 0.7);
      }
    }

    if (superpowers.length === 0 && countries.size > 0) {
      // No superpowers — promote the strongest
      const strongest = Array.from(countries.values())
        .sort((a, b) => (b.military || 0) - (a.military || 0))[0];
      if (strongest && strongest.military && strongest.military > 80) {
        strongest.status = 'superpower';
      }
    }

    // Ensure major countries have at least 1 ally
    for (const country of countries.values()) {
      if (country.status === 'major' && (!country.allies || country.allies.length === 0)) {
        // Find nearby country to ally with
        const others = Array.from(countries.keys()).filter(k => k !== country.code);
        if (others.length > 0) {
          country.allies = [others[0]];
        }
      }
    }
  }

  /**
   * Update world state after a time jump
   */
  async updateWorldState(
    currentState: WorldState,
    events: string[],
    jumpDays: number
  ): Promise<WorldState> {
    // For now, apply simple rules based on events
    // In the future, this could use LLM to generate more nuanced updates

    const updatedCountries = new Map(currentState.countries);

    for (const country of updatedCountries.values()) {
      // Simple growth/decline based on events
      for (const event of events) {
        if (event.includes('war') || event.includes('conflict')) {
          country.military = Math.min(200, (country.military || 50) * 1.1);
          country.population = Math.max(1_000_000, (country.population || 10_000_000) * 0.95);
        }
        if (event.includes('economic') || event.includes('crisis')) {
          country.gdp = Math.max(10, (country.gdp || 50) * 0.9);
        }
        if (event.includes('growth') || event.includes('boom')) {
          country.gdp = Math.min(200, (country.gdp || 50) * 1.1);
        }
      }

      // Natural growth (0.1% per month)
      const months = Math.floor(jumpDays / 30);
      const growth = 1 + (0.001 * months);
      country.population = Math.floor((country.population || 10_000_000) * growth);
    }

    return {
      date: this.advanceDate(currentState.date, jumpDays),
      countries: updatedCountries,
    };
  }

  /**
   * Advance date by N days
   */
  private advanceDate(date: string, days: number): string {
    const d = new Date(date);
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  }

  /**
   * Get summary of world state for prompts
   */
  getWorldSummary(state: WorldState): string {
    const lines: string[] = [];

    lines.push(`## Mondo al ${state.date}`);
    lines.push('');

    // Group by status
    const superpowers = Array.from(state.countries.values()).filter(c => c.status === 'superpower');
    const majors = Array.from(state.countries.values()).filter(c => c.status === 'major');
    const regionals = Array.from(state.countries.values()).filter(c => c.status === 'regional');

    if (superpowers.length > 0) {
      lines.push('### Superpotenze');
      for (const c of superpowers) {
        lines.push(`- **${c.name}** (${c.code}): ${c.population?.toLocaleString('it-IT')} abitanti, PIL: ${c.gdp}, Militare: ${c.military}`);
        if (c.allies && c.allies.length > 0) {
          lines.push(`  Alleati: ${c.allies.join(', ')}`);
        }
        if (c.enemies && c.enemies.length > 0) {
          lines.push(`  Nemici: ${c.enemies.join(', ')}`);
        }
      }
      lines.push('');
    }

    if (majors.length > 0) {
      lines.push('### Grandi potenze');
      for (const c of majors) {
        lines.push(`- ${c.name} (${c.code}): ${c.population?.toLocaleString('it-IT')} abitanti`);
      }
      lines.push('');
    }

    return lines.join('\n');
  }
}
