/** M05 µ4 — personale e ricerca riproducibile (MAT10/MAT22). */
import crypto from 'crypto';import {IntString,intToString,parseInteger} from '../../domain/quantities';
export interface WorkforceDemand { readonly id:string;readonly qualification:string;readonly requestedPersons:IntString;readonly priority:number;readonly queueSequence:number; }
export function allocateWorkforce(pool:Readonly<Record<string,IntString>>,demands:readonly WorkforceDemand[]):Readonly<Record<string,IntString>>{const free=new Map(Object.entries(pool).map(([k,v])=>[k,parseInteger(v,'pool')]));const granted:Record<string,IntString>={};for(const d of [...demands].sort((a,b)=>a.priority-b.priority||a.queueSequence-b.queueSequence)){const req=parseInteger(d.requestedPersons,'requested');if(req<0n)throw new Error('personale negativo');const available=free.get(d.qualification)??0n;const take=req<available?req:available;free.set(d.qualification,available-take);granted[d.id]=intToString(take);}return granted;}
export interface ResearchMilestone { readonly id:string;readonly requiredWork:IntString;readonly costMinorUnits:IntString;readonly successNumerator:IntString;readonly successDenominator:IntString; }
export interface ResearchState { readonly seed:string;readonly milestoneId:string;readonly completedWork:IntString;readonly spentMinorUnits:IntString;readonly resolved:boolean;readonly success?:boolean; }
function draw(seed:string,milestone:string):bigint{return BigInt('0x'+crypto.createHash('sha256').update(`${seed}:${milestone}`).digest('hex').slice(0,16));}
/** Un milestone costa/lavora solo quanto esplicitamente passato; esito da seed stabile al completamento. */
export function advanceResearch(m:ResearchMilestone,state:ResearchState,work:IntString,cost:IntString):{state:ResearchState;charged:IntString}{if(state.milestoneId!==m.id||state.resolved)throw new Error('milestone non avanzabile');const w=parseInteger(work,'work');const c=parseInteger(cost,'cost');if(w<0n||c<0n)throw new Error('work/cost negativi');const total=parseInteger(m.requiredWork,'required');const next=(parseInteger(state.completedWork,'completed')+w)>total?total:parseInteger(state.completedWork,'completed')+w;const spent=parseInteger(state.spentMinorUnits,'spent')+c;const done=next===total&&spent>=parseInteger(m.costMinorUnits,'required cost');let success:boolean|undefined;const n=parseInteger(m.successNumerator,'numerator');const d=parseInteger(m.successDenominator,'denominator');if(d<=0n||n<0n||n>d)throw new Error('probabilità milestone non valida');if(done)success=(draw(state.seed,m.id)%d)<n;return{state:{...state,completedWork:intToString(next),spentMinorUnits:intToString(spent),resolved:done,success},charged:intToString(c)};}
