/** M05 µ1 — WBS/DAG e stati progetto, puro (§7.1). */
import { IntString,intToString,isIdString,parseInteger } from '../../domain/quantities';
export type ProjectStatus='planned'|'authorized'|'active'|'blocked'|'commissioning'|'completed'|'cancelled'|'failed';
export interface ProjectPhase { readonly id:string; readonly dependencyIds:readonly string[]; readonly workload:IntString; readonly minDays:number; readonly budget?:{readonly currencyId:string;readonly minorUnits:IntString}; readonly inputs?:readonly {readonly resourceId:string;readonly baseUnits:IntString}[]; readonly assetId?:string; readonly requiresCommissioning:boolean; }
export interface ProjectPlan { readonly id:string; readonly phases:readonly ProjectPhase[]; }
export interface PhaseState { readonly id:string; readonly status:'planned'|'active'|'blocked'|'commissioning'|'completed'|'cancelled'|'failed'; readonly completedWork:IntString; readonly workedDays:number; }
export interface ProjectState { readonly id:string; readonly status:ProjectStatus; readonly phases:readonly PhaseState[]; /** Asset conclusi, attivabili solo al confine seguente. */ readonly pendingAssets:readonly string[]; readonly activatedAssets:readonly string[]; }
export class ProjectSchemaError extends Error { constructor(message:string){super(message);this.name='ProjectSchemaError';} }
function phaseMap(plan:ProjectPlan){return new Map(plan.phases.map(x=>[x.id,x]));}
export function validateProjectPlan(plan:ProjectPlan):void{if(!isIdString(plan.id)||!plan.phases.length)throw new ProjectSchemaError('project id/fasi non validi');const ids=new Set<string>();for(const p of plan.phases){if(!isIdString(p.id)||ids.has(p.id)||!Number.isInteger(p.minDays)||p.minDays<1||parseInteger(p.workload,'workload')<=0n)throw new ProjectSchemaError('fase non valida');ids.add(p.id);for(const d of p.dependencyIds)if(!isIdString(d))throw new ProjectSchemaError('dipendenza non valida');}const by=phaseMap(plan);const visiting=new Set<string>();const done=new Set<string>();const visit=(id:string):void=>{if(done.has(id))return;if(visiting.has(id))throw new ProjectSchemaError('DAG fasi ciclico');const p=by.get(id);if(!p)throw new ProjectSchemaError('dipendenza fase sconosciuta');visiting.add(id);p.dependencyIds.forEach(visit);visiting.delete(id);done.add(id);};plan.phases.forEach(p=>visit(p.id));}
export function createProject(plan:ProjectPlan):ProjectState{validateProjectPlan(plan);return{id:plan.id,status:'planned',phases:plan.phases.map(p=>({id:p.id,status:'planned',completedWork:'0',workedDays:0})),pendingAssets:[],activatedAssets:[]};}
export function authorizeProject(state:ProjectState):ProjectState{if(state.status!=='planned')throw new ProjectSchemaError('solo planned può essere authorized');return{...state,status:'authorized'};}
/** Attiva una fase solo dopo dipendenze completate; nessun asset/costo è creato qui. */
export function activatePhase(plan:ProjectPlan,state:ProjectState,phaseId:string):ProjectState{if(state.status!=='authorized'&&state.status!=='active'&&state.status!=='blocked')throw new ProjectSchemaError('progetto non attivabile');const phase=phaseMap(plan).get(phaseId);const current=state.phases.find(x=>x.id===phaseId);if(!phase||!current)throw new ProjectSchemaError('fase sconosciuta');if(current.status!=='planned'&&current.status!=='blocked')throw new ProjectSchemaError('fase già attiva/chiusa');const complete=new Set(state.phases.filter(x=>x.status==='completed').map(x=>x.id));if(phase.dependencyIds.some(x=>!complete.has(x)))return{...state,status:'blocked',phases:state.phases.map(x=>x.id===phaseId?{...x,status:'blocked'}:x)};return{...state,status:'active',phases:state.phases.map(x=>x.id===phaseId?{...x,status:'active'}:x)};}
/** Un giorno di lavoro: zero fattori → blocked e zero progresso; non esistono tick LLM gratuiti. */
export function advancePhaseDay(plan:ProjectPlan,state:ProjectState,phaseId:string,workDone:IntString):ProjectState{const phase=phaseMap(plan).get(phaseId);const current=state.phases.find(x=>x.id===phaseId);if(!phase||!current)throw new ProjectSchemaError('fase sconosciuta');if(current.status!=='active'&&current.status!=='blocked')throw new ProjectSchemaError('fase non lavorabile');const work=parseInteger(workDone,'workDone');if(work<0n)throw new ProjectSchemaError('workDone negativo');if(work===0n)return{...state,status:'blocked',phases:state.phases.map(x=>x.id===phaseId?{...x,status:'blocked'}:x)};const total=parseInteger(phase.workload,'workload');const nextWork=(parseInteger(current.completedWork,'completed')+work)>total?total:parseInteger(current.completedWork,'completed')+work;const days=current.workedDays+1;const done=nextWork===total&&days>=phase.minDays;const phaseStatus:PhaseState['status']=done?(phase.requiresCommissioning?'commissioning':'completed'):'active';const phases=state.phases.map(x=>x.id===phaseId?{...x,status:phaseStatus,completedWork:intToString(nextWork),workedDays:days}:x);const pending=done&&!phase.requiresCommissioning&&phase.assetId?[...state.pendingAssets,phase.assetId]:state.pendingAssets;return{...state,status:done?(phase.requiresCommissioning?'commissioning':'active'):'active',phases,pendingAssets:pending};}
/** Collaudo esplicito: non è implicato da accepted o da un testo LLM. */
export function completeCommissioning(plan:ProjectPlan,state:ProjectState,phaseId:string):ProjectState{const phase=phaseMap(plan).get(phaseId);const current=state.phases.find(x=>x.id===phaseId);if(!phase||!current||current.status!=='commissioning')throw new ProjectSchemaError('fase non in commissioning');const phases=state.phases.map(x=>x.id===phaseId?{...x,status:'completed' as const}:x);const pending=phase.assetId?[...state.pendingAssets,phase.assetId]:state.pendingAssets;const allDone=phases.every(x=>x.status==='completed');return{...state,status:allDone?'completed':'active',phases,pendingAssets:pending};}
/** Confine temporale: solo qui gli asset pending diventano operativi. */
export function activatePendingAssets(state:ProjectState):ProjectState{return{...state,activatedAssets:[...state.activatedAssets,...state.pendingAssets],pendingAssets:[]};}
export function cancelProject(state:ProjectState):ProjectState{if(['completed','failed','cancelled'].includes(state.status))throw new ProjectSchemaError('progetto terminale');return{...state,status:'cancelled',phases:state.phases.map(x=>x.status==='completed'?x:{...x,status:'cancelled' as const})};}
