/** M05 µ5 — costi fase/residui: annullare non riscrive il passato (§6.2). */
import {IntString,intToString,parseInteger} from '../../domain/quantities';
export interface ProjectFunding { readonly reservationId:string; readonly initialReserved:IntString; readonly remainingReserved:IntString; readonly spent:IntString; readonly released:IntString; }
export interface CancellationResult { readonly funding:ProjectFunding; readonly releaseReservationId:string; readonly releaseAmount:IntString; readonly sunkCost:IntString; }
export function createProjectFunding(reservationId:string,amount:IntString):ProjectFunding{const n=parseInteger(amount,'amount');if(n<0n)throw new Error('amount negativo');return{reservationId,initialReserved:amount,remainingReserved:amount,spent:'0',released:'0'};}
/** Spesa reale: converte una parte della riserva in costo già sostenuto. */
export function spendProjectFunding(state:ProjectFunding,amount:IntString):ProjectFunding{const n=parseInteger(amount,'amount');const remaining=parseInteger(state.remainingReserved,'remaining');if(n<0n||n>remaining)throw new Error('spesa oltre riserva');return{...state,remainingReserved:intToString(remaining-n),spent:intToString(parseInteger(state.spent,'spent')+n)};}
/** Nuovo comando di annullamento: da consegnare a ReservationService.release. */
export function cancelProjectFunding(state:ProjectFunding):CancellationResult{return{funding:{...state,remainingReserved:'0',released:intToString(parseInteger(state.released,'released')+parseInteger(state.remainingReserved,'remaining'))},releaseReservationId:state.reservationId,releaseAmount:state.remainingReserved,sunkCost:state.spent};}
/** Snapshot JSON esplicito: default legacy assente è unknown, non saldo inventato. */
export function restoreProjectFunding(value:unknown):ProjectFunding|null{if(!value||typeof value!=='object'||Array.isArray(value))return null;const x=value as Record<string,unknown>;if(typeof x.reservationId!=='string'||typeof x.initialReserved!=='string'||typeof x.remainingReserved!=='string'||typeof x.spent!=='string'||typeof x.released!=='string')return null;try{const i=parseInteger(x.initialReserved,'initial');const r=parseInteger(x.remainingReserved,'remaining');const s=parseInteger(x.spent,'spent');const released=parseInteger(x.released,'released');if(i<0n||r<0n||s<0n||released<0n||r+s+released!==i)return null;return{reservationId:x.reservationId,initialReserved:x.initialReserved,remainingReserved:x.remainingReserved,spent:x.spent,released:x.released};}catch{return null;}}
