/** M04 µ5 — bridge lavoro↔ledger: commit fisici idempotenti, niente LLM. */
import { LedgerEntryInput } from '../domain/ledger';
import { appendLedgerEntries } from '../repositories/ledger.repository';
import { PendingOutput,WorkState,releaseOutputs,tickWorkDay } from '../core/economy/WorkEngine';
import { ExecutionRecipe,ProductionAvailability } from '../core/economy/ProductionEngine';
export interface WorkCommit { readonly state:WorkState; readonly pendingForBoundary:readonly PendingOutput[]; readonly appended:number; }
function consumptionEntries(effectId:string,holder:string,recipe:ExecutionRecipe,consumed:readonly {resourceId:string;baseUnits:string}[],energy:{resourceId:string;baseUnits:string},date:string):LedgerEntryInput[]{const entries:LedgerEntryInput[]=[];for(const item of consumed){if(item.baseUnits!=='0')entries.push({effectId,entryIndex:entries.length,cause:'consumo',kind:'material',unitId:item.resourceId,fromRef:holder,toRef:null,ownerRef:holder,delta:item.baseUnits,atDate:date});}if(energy.baseUnits!=='0')entries.push({effectId,entryIndex:entries.length,cause:'consumo',kind:'material',unitId:energy.resourceId,fromRef:holder,toRef:null,ownerRef:holder,delta:energy.baseUnits,atDate:date});return entries;}
/** Consuma solo input/energia del lavoro effettivo; output resta pending nello stato. */
export function commitWorkDay(gameId:string,branchId:string,effectId:string,state:WorkState,recipe:ExecutionRecipe,date:string,availability:ProductionAvailability,holderRef:string):WorkCommit{const tick=tickWorkDay(state,recipe,date,availability);const entries=consumptionEntries(effectId,holderRef,recipe,tick.production.consumed,tick.production.energyConsumed,date);const result=entries.length?appendLedgerEntries(gameId,branchId,entries):{appended:0,duplicates:0};return{state:tick.state,pendingForBoundary:tick.state.pending,appended:result.appended};}
/** Rilascia output maturato e lo accredita al ledger; retry è verificato dal ledger. */
export function commitOutputBoundary(gameId:string,branchId:string,effectId:string,state:WorkState,date:string,holderRef:string):{state:WorkState;appended:number}{const released=releaseOutputs(state,date);const entries=released.released.filter(x=>x.baseUnits!=='0').map((x,index):LedgerEntryInput=>({effectId,entryIndex:index,cause:'produzione',kind:'material',unitId:x.resourceId,fromRef:null,toRef:holderRef,ownerRef:holderRef,delta:x.baseUnits,atDate:date}));const result=entries.length?appendLedgerEntries(gameId,branchId,entries):{appended:0,duplicates:0};return{state:released.state,appended:result.appended};}
