/** M02 µ4 — stanziamento, cassa, debito, escrow, cashflow/ratei (§6.1). */
import db, { withCanonicalTransaction } from '../database';
import { LedgerEntryInput, validateLedgerEntry } from '../domain/ledger';
import { IntString, intToString, parseInteger, rational } from '../domain/quantities';
import { appendLedgerEntries, reconstructBalances } from '../repositories/ledger.repository';
import { consumeReservation } from './ReservationService';

export class FinanceError extends Error {
  readonly code: string;
  constructor(code: string, message: string) { super(message); this.name = 'FinanceError'; this.code = code; }
}
export class FinanceConflictError extends FinanceError {
  constructor(message: string) { super('finance_conflict', message); this.name = 'FinanceConflictError'; }
}

export interface MoneyAccount { readonly ref: string; readonly currencyId: string; }
export interface AppropriationInput { readonly appropriationId: string; readonly account: MoneyAccount; readonly authorizedAmount: IntString; }
export interface DebtInput { readonly debtId: string; readonly lender: MoneyAccount; readonly borrower: MoneyAccount; readonly limitAmount: IntString; readonly rate: { numerator: IntString; denominator: IntString }; readonly maturityDate: string; }
export interface EscrowInput { readonly escrowId: string; readonly buyer: MoneyAccount; readonly seller: MoneyAccount; readonly escrowRef: string; readonly amount: IntString; }
export interface CashflowInput { readonly cashflowId: string; readonly debtor: MoneyAccount; readonly creditor: MoneyAccount; readonly amount: IntString; readonly dueDate: string; readonly legalPriority: number; readonly partialAllowed: boolean; readonly shortagePolicy: 'arrears' | 'default'; }

interface OperationRow { operation_type: string; amount: IntString; reference_id: string | null; ledger_effect_id: string | null; ledger_entry_index: number | null; detail: string | null; }
interface AmountRow { authorized_amount: IntString; committed_amount: IntString; spent_amount: IntString; account_ref: string; currency_id: string; game_id: string; }
interface DebtRow { game_id: string; lender_ref: string; borrower_ref: string; currency_id: string; limit_amount: IntString; rate_numerator: IntString; rate_denominator: IntString; maturity_date: string; drawn_amount: IntString; principal_outstanding: IntString; accrued_interest: IntString; carry_numerator: IntString; }
interface EscrowRow { game_id: string; buyer_ref: string; seller_ref: string; escrow_ref: string; currency_id: string; amount: IntString; status: 'draft'|'funded'|'released'|'refunded'; }
interface CashflowRow { game_id: string; debtor_ref: string; creditor_ref: string; currency_id: string; due_date: string; amount: IntString; outstanding_amount: IntString; legal_priority: number; partial_allowed: number; shortage_policy: 'arrears'|'default'; status: 'scheduled'|'paid'|'arrears'|'default'; }
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const DATE = /^\d{4}-\d{2}-\d{2}$/;
function id(value: string, label: string): void { if (typeof value !== 'string' || !ID.test(value)) throw new FinanceError('bad_id', `${label} non valido`); }
/** Difesa in profondità (quarta revisione M3): round-trip UTC, non solo regex. */
function date(value: string, label: string): void { if (!DATE.test(value) || !Number.isFinite(Date.parse(`${value}T00:00:00.000Z`)) || new Date(Date.parse(`${value}T00:00:00.000Z`)).toISOString().slice(0, 10) !== value) throw new FinanceError('bad_date', `${label} deve essere una data canonica YYYY-MM-DD`); }
function positive(value: IntString, label: string): bigint { const n = parseInteger(value, label); if (n <= 0n) throw new FinanceError('bad_amount', `${label} deve essere > 0`); return n; }
function account(value: MoneyAccount, label: string): void { if (!value.ref || !value.currencyId) throw new FinanceError('bad_account', `${label} incompleto`); }
function op(branchId: string, kind: string, entityId: string, operationId: string): OperationRow | null { return (db.prepare(`SELECT operation_type,amount,reference_id,ledger_effect_id,ledger_entry_index,detail FROM finance_operations WHERE branch_id=? AND entity_kind=? AND entity_id=? AND operation_id=?`).get(branchId, kind, entityId, operationId) as OperationRow | undefined) ?? null; }
function record(branchId: string, kind: string, entityId: string, operationId: string, operationType: string, amount: IntString, referenceId: string | null, entry: LedgerEntryInput | null, detail: string | null): void { db.prepare(`INSERT INTO finance_operations (branch_id,entity_kind,entity_id,operation_id,operation_type,amount,reference_id,ledger_effect_id,ledger_entry_index,detail) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(branchId,kind,entityId,operationId,operationType,amount,referenceId,entry?.effectId ?? null,entry?.entryIndex ?? null,detail); }
function verify(existing: OperationRow, type: string, amount: IntString, reference: string | null, entry: LedgerEntryInput | null, detail: string | null): void { if (existing.operation_type!==type || existing.amount!==amount || existing.reference_id!==reference || existing.ledger_effect_id!==(entry?.effectId ?? null) || existing.ledger_entry_index!==(entry?.entryIndex ?? null) || existing.detail!==detail) throw new FinanceConflictError('operationId già registrato con contenuto diverso'); }
function balance(branchId: string, a: MoneyAccount): bigint { const row=reconstructBalances(branchId).accounts.find(x=>x.ref===a.ref && x.currencyId===a.currencyId); return parseInteger(row?.balance ?? '0','cash'); }
function sameEntry(entry: LedgerEntryInput, effect: string, cause: LedgerEntryInput['cause'], from: string, to: string, currency: string, amount: IntString): void { validateLedgerEntry(entry); if(entry.effectId!==effect||entry.kind!=='money'||entry.cause!==cause||entry.fromRef!==from||entry.toRef!==to||entry.unitId!==currency||entry.delta!==amount) throw new FinanceError('ledger_mismatch','movimento ledger non coerente con il contratto'); }

export function createAppropriation(gameId: string, branchId: string, input: AppropriationInput): boolean {
 id(input.appropriationId,'appropriationId'); account(input.account,'account'); positive(input.authorizedAmount,'authorizedAmount');
 return withCanonicalTransaction(()=>{ const old=db.prepare('SELECT authorized_amount,account_ref,currency_id,game_id FROM finance_appropriations WHERE branch_id=? AND appropriation_id=?').get(branchId,input.appropriationId) as {authorized_amount:IntString;account_ref:string;currency_id:string;game_id:string}|undefined; if(old){if(old.authorized_amount!==input.authorizedAmount||old.account_ref!==input.account.ref||old.currency_id!==input.account.currencyId||old.game_id!==gameId)throw new FinanceConflictError('stanziamento già esistente diverso');return false;} db.prepare(`INSERT INTO finance_appropriations(game_id,branch_id,appropriation_id,account_ref,currency_id,authorized_amount) VALUES(?,?,?,?,?,?)`).run(gameId,branchId,input.appropriationId,input.account.ref,input.account.currencyId,input.authorizedAmount);return true; });
}
export function getAppropriation(branchId: string, appropriationId: string): { authorized: IntString; committed: IntString; spent: IntString; residual: IntString; cash: IntString } | null {
 const row=db.prepare('SELECT authorized_amount,committed_amount,spent_amount,account_ref,currency_id,game_id FROM finance_appropriations WHERE branch_id=? AND appropriation_id=?').get(branchId,appropriationId) as AmountRow|undefined; if(!row)return null; const authorized=parseInteger(row.authorized_amount,'authorized');const committed=parseInteger(row.committed_amount,'committed');const spent=parseInteger(row.spent_amount,'spent'); return {authorized:row.authorized_amount,committed:row.committed_amount,spent:row.spent_amount,residual:intToString(authorized-committed-spent),cash:intToString(balance(branchId,{ref:row.account_ref,currencyId:row.currency_id}))};
}
/** Impegno autorizzativo, distinto sia dalla cassa sia da una riserva M02 µ3. */
export function commitAppropriation(branchId: string, appropriationId: string, operationId: string, amount: IntString): boolean {
 id(operationId,'operationId'); positive(amount,'amount'); return withCanonicalTransaction(()=>{const row=db.prepare('SELECT authorized_amount,committed_amount,spent_amount FROM finance_appropriations WHERE branch_id=? AND appropriation_id=?').get(branchId,appropriationId) as Pick<AmountRow,'authorized_amount'|'committed_amount'|'spent_amount'>|undefined;if(!row)throw new FinanceError('not_found','stanziamento non trovato');const old=op(branchId,'appropriation',appropriationId,operationId);if(old){verify(old,'commit',amount,null,null,null);return false;}const residual=parseInteger(row.authorized_amount,'authorized')-parseInteger(row.committed_amount,'committed')-parseInteger(row.spent_amount,'spent');if(positive(amount,'amount')>residual)throw new FinanceError('appropriation_exhausted','stanziamento residuo insufficiente');db.prepare('UPDATE finance_appropriations SET committed_amount=? WHERE branch_id=? AND appropriation_id=?').run(intToString(parseInteger(row.committed_amount,'committed')+positive(amount,'amount')),branchId,appropriationId);record(branchId,'appropriation',appropriationId,operationId,'commit',amount,null,null,null);return true;});
}

export function createDebt(gameId:string,branchId:string,input:DebtInput):boolean { id(input.debtId,'debtId');account(input.lender,'lender');account(input.borrower,'borrower');if(input.lender.currencyId!==input.borrower.currencyId||input.lender.ref===input.borrower.ref)throw new FinanceError('bad_debt','parti/valuta debito non valide');positive(input.limitAmount,'limitAmount');date(input.maturityDate,'maturityDate');const r=rational(input.rate.numerator,input.rate.denominator);if(parseInteger(r.numerator,'rate')<0n)throw new FinanceError('bad_rate','tasso negativo vietato');return withCanonicalTransaction(()=>{const old=db.prepare('SELECT limit_amount,rate_numerator,rate_denominator,maturity_date,lender_ref,borrower_ref,currency_id,game_id FROM finance_debts WHERE branch_id=? AND debt_id=?').get(branchId,input.debtId) as {limit_amount:IntString;rate_numerator:IntString;rate_denominator:IntString;maturity_date:string;lender_ref:string;borrower_ref:string;currency_id:string;game_id:string}|undefined;if(old){if(old.limit_amount!==input.limitAmount||old.rate_numerator!==r.numerator||old.rate_denominator!==r.denominator||old.maturity_date!==input.maturityDate||old.lender_ref!==input.lender.ref||old.borrower_ref!==input.borrower.ref||old.currency_id!==input.lender.currencyId||old.game_id!==gameId)throw new FinanceConflictError('debito già esistente diverso');return false;}db.prepare(`INSERT INTO finance_debts(game_id,branch_id,debt_id,lender_ref,borrower_ref,currency_id,limit_amount,rate_numerator,rate_denominator,maturity_date) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(gameId,branchId,input.debtId,input.lender.ref,input.borrower.ref,input.lender.currencyId,input.limitAmount,r.numerator,r.denominator,input.maturityDate);return true;}); }
function debt(branch:string,idValue:string):DebtRow {const row=db.prepare('SELECT game_id,lender_ref,borrower_ref,currency_id,limit_amount,rate_numerator,rate_denominator,maturity_date,drawn_amount,principal_outstanding,accrued_interest,carry_numerator FROM finance_debts WHERE branch_id=? AND debt_id=?').get(branch,idValue) as DebtRow|undefined;if(!row)throw new FinanceError('not_found','debito non trovato');return row;}
export function drawDebt(game:string,branch:string,debtId:string,operationId:string,amount:IntString,ledgerEntry:LedgerEntryInput):boolean {id(operationId,'operationId');positive(amount,'amount');return withCanonicalTransaction(()=>{const d=debt(branch,debtId);sameEntry(ledgerEntry,operationId,'prestito_erogato',d.lender_ref,d.borrower_ref,d.currency_id,amount);const old=op(branch,'debt',debtId,operationId);if(old){verify(old,'draw',amount,null,ledgerEntry,null);appendLedgerEntries(game,branch,[ledgerEntry]);return false;}if(parseInteger(d.drawn_amount,'drawn')+positive(amount,'amount')>parseInteger(d.limit_amount,'limit'))throw new FinanceError('debt_limit','limite debito superato');appendLedgerEntries(game,branch,[ledgerEntry]);db.prepare('UPDATE finance_debts SET drawn_amount=?,principal_outstanding=? WHERE branch_id=? AND debt_id=?').run(intToString(parseInteger(d.drawn_amount,'drawn')+positive(amount,'amount')),intToString(parseInteger(d.principal_outstanding,'principal')+positive(amount,'amount')),branch,debtId);record(branch,'debt',debtId,operationId,'draw',amount,null,ledgerEntry,null);return true;});}
export function getDebt(branch:string,debtId:string):{drawn:IntString;principal:IntString;accruedInterest:IntString;carry:IntString;limit:IntString}|null{const row=db.prepare('SELECT drawn_amount,principal_outstanding,accrued_interest,carry_numerator,limit_amount FROM finance_debts WHERE branch_id=? AND debt_id=?').get(branch,debtId) as {drawn_amount:IntString;principal_outstanding:IntString;accrued_interest:IntString;carry_numerator:IntString;limit_amount:IntString}|undefined;return row?{drawn:row.drawn_amount,principal:row.principal_outstanding,accruedInterest:row.accrued_interest,carry:row.carry_numerator,limit:row.limit_amount}:null;}
/** ACT/365F: carry=(principal*rateNumerator*days+carry) mod (rateDenominator*365). */
export function accrueDebtInterest(branch:string,debtId:string,operationId:string,days:number):{interest:IntString;carry:IntString;accrued:IntString;applied:boolean}{id(operationId,'operationId');if(!Number.isInteger(days)||days<0||days>36600)throw new FinanceError('bad_days','days deve essere intero 0..36600');return withCanonicalTransaction(()=>{const d=debt(branch,debtId);const detail=String(days);const old=op(branch,'debt',debtId,operationId);if(old){verify(old,'accrue',old.amount,null,null,detail);return {interest:old.amount,carry:d.carry_numerator,accrued:d.accrued_interest,applied:false};}const denominator=parseInteger(d.rate_denominator,'rate denominator')*365n;const gross=parseInteger(d.principal_outstanding,'principal')*parseInteger(d.rate_numerator,'rate numerator')*BigInt(days)+parseInteger(d.carry_numerator,'carry');const interest=gross/denominator;const carry=gross-interest*denominator;const accrued=parseInteger(d.accrued_interest,'accrued')+interest;db.prepare('UPDATE finance_debts SET accrued_interest=?,carry_numerator=? WHERE branch_id=? AND debt_id=?').run(intToString(accrued),intToString(carry),branch,debtId);record(branch,'debt',debtId,operationId,'accrue',intToString(interest),null,null,detail);return {interest:intToString(interest),carry:intToString(carry),accrued:intToString(accrued),applied:true};});}

export function createEscrow(game:string,branch:string,input:EscrowInput):boolean{id(input.escrowId,'escrowId');account(input.buyer,'buyer');account(input.seller,'seller');if(input.buyer.currencyId!==input.seller.currencyId||!input.escrowRef||new Set([input.buyer.ref,input.seller.ref,input.escrowRef]).size!==3)throw new FinanceError('bad_escrow','buyer/seller/escrow devono essere conti distinti stessa valuta');positive(input.amount,'amount');return withCanonicalTransaction(()=>{const old=db.prepare('SELECT game_id,buyer_ref,seller_ref,escrow_ref,currency_id,amount FROM finance_escrows WHERE branch_id=? AND escrow_id=?').get(branch,input.escrowId) as Omit<EscrowRow,'status'>|undefined;if(old){if(old.game_id!==game||old.buyer_ref!==input.buyer.ref||old.seller_ref!==input.seller.ref||old.escrow_ref!==input.escrowRef||old.currency_id!==input.buyer.currencyId||old.amount!==input.amount)throw new FinanceConflictError('escrow già esistente diverso');return false;}db.prepare(`INSERT INTO finance_escrows(game_id,branch_id,escrow_id,buyer_ref,seller_ref,escrow_ref,currency_id,amount,status) VALUES(?,?,?,?,?,?,?,?, 'draft')`).run(game,branch,input.escrowId,input.buyer.ref,input.seller.ref,input.escrowRef,input.buyer.currencyId,input.amount);return true;});}
function escrow(branch:string,idValue:string):EscrowRow{const row=db.prepare('SELECT game_id,buyer_ref,seller_ref,escrow_ref,currency_id,amount,status FROM finance_escrows WHERE branch_id=? AND escrow_id=?').get(branch,idValue) as EscrowRow|undefined;if(!row)throw new FinanceError('not_found','escrow non trovato');return row;}
export function depositEscrow(game:string,branch:string,escrowId:string,operationId:string,reservationId:string,ledgerEntry:LedgerEntryInput):boolean{id(operationId,'operationId');return withCanonicalTransaction(()=>{const e=escrow(branch,escrowId);sameEntry(ledgerEntry,operationId,'pagamento',e.buyer_ref,e.escrow_ref,e.currency_id,e.amount);const old=op(branch,'escrow',escrowId,operationId);if(old){verify(old,'deposit',e.amount,reservationId,ledgerEntry,null);consumeReservation(game,branch,reservationId,{operationId,amount:e.amount,ledgerEntry});return false;}if(e.status!=='draft')throw new FinanceError('bad_escrow_state','escrow non in draft');consumeReservation(game,branch,reservationId,{operationId,amount:e.amount,ledgerEntry});db.prepare("UPDATE finance_escrows SET status='funded' WHERE branch_id=? AND escrow_id=?").run(branch,escrowId);record(branch,'escrow',escrowId,operationId,'deposit',e.amount,reservationId,ledgerEntry,null);return true;});}
function settleEscrow(game:string,branch:string,escrowId:string,operationId:string,outcome:'released'|'refunded',ledgerEntry:LedgerEntryInput):boolean{id(operationId,'operationId');return withCanonicalTransaction(()=>{const e=escrow(branch,escrowId);const to=outcome==='released'?e.seller_ref:e.buyer_ref;const cause:LedgerEntryInput['cause']=outcome==='released'?'pagamento':'rimborso';sameEntry(ledgerEntry,operationId,cause,e.escrow_ref,to,e.currency_id,e.amount);const old=op(branch,'escrow',escrowId,operationId);if(old){verify(old,outcome,e.amount,null,ledgerEntry,null);appendLedgerEntries(game,branch,[ledgerEntry]);return false;}if(e.status!=='funded')throw new FinanceError('bad_escrow_state','escrow non finanziato o già chiuso');appendLedgerEntries(game,branch,[ledgerEntry]);db.prepare('UPDATE finance_escrows SET status=? WHERE branch_id=? AND escrow_id=?').run(outcome,branch,escrowId);record(branch,'escrow',escrowId,operationId,outcome,e.amount,null,ledgerEntry,null);return true;});}
export const releaseEscrow=(game:string,branch:string,idValue:string,opId:string,entry:LedgerEntryInput)=>settleEscrow(game,branch,idValue,opId,'released',entry);
export const refundEscrow=(game:string,branch:string,idValue:string,opId:string,entry:LedgerEntryInput)=>settleEscrow(game,branch,idValue,opId,'refunded',entry);

export function createCashflow(game:string,branch:string,input:CashflowInput):boolean{id(input.cashflowId,'cashflowId');account(input.debtor,'debtor');account(input.creditor,'creditor');if(input.debtor.currencyId!==input.creditor.currencyId||input.debtor.ref===input.creditor.ref)throw new FinanceError('bad_cashflow','parti/valuta cashflow non valide');positive(input.amount,'amount');date(input.dueDate,'dueDate');if(!Number.isInteger(input.legalPriority)||input.legalPriority<0)throw new FinanceError('bad_priority','priorità non valida');return withCanonicalTransaction(()=>{const old=db.prepare('SELECT game_id,debtor_ref,creditor_ref,currency_id,due_date,amount,legal_priority,partial_allowed,shortage_policy FROM finance_cashflows WHERE branch_id=? AND cashflow_id=?').get(branch,input.cashflowId) as Omit<CashflowRow,'outstanding_amount'|'status'>|undefined;if(old){if(old.game_id!==game||old.debtor_ref!==input.debtor.ref||old.creditor_ref!==input.creditor.ref||old.currency_id!==input.debtor.currencyId||old.due_date!==input.dueDate||old.amount!==input.amount||old.legal_priority!==input.legalPriority||Boolean(old.partial_allowed)!==input.partialAllowed||old.shortage_policy!==input.shortagePolicy)throw new FinanceConflictError('cashflow già esistente diverso');return false;}db.prepare(`INSERT INTO finance_cashflows(game_id,branch_id,cashflow_id,debtor_ref,creditor_ref,currency_id,due_date,amount,outstanding_amount,legal_priority,partial_allowed,shortage_policy,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'scheduled')`).run(game,branch,input.cashflowId,input.debtor.ref,input.creditor.ref,input.debtor.currencyId,input.dueDate,input.amount,input.amount,input.legalPriority,input.partialAllowed?1:0,input.shortagePolicy);return true;});}
/** Liquida tutti gli obblighi scaduti in priorità legale; l'insoluto resta arrears/default, mai cancellato. */
export function settleDueCashflows(game:string,branch:string,asOfDate:string):ReadonlyArray<{cashflowId:string;paid:IntString;status:string}>{date(asOfDate,'asOfDate');return withCanonicalTransaction(()=>{const rows=db.prepare(`SELECT game_id,debtor_ref,creditor_ref,currency_id,due_date,amount,outstanding_amount,legal_priority,partial_allowed,shortage_policy,status,cashflow_id FROM finance_cashflows WHERE branch_id=? AND due_date<=? AND status IN ('scheduled','arrears') ORDER BY legal_priority ASC,due_date ASC,cashflow_id ASC`).all(branch,asOfDate) as Array<CashflowRow&{cashflow_id:string}>;const out:Array<{cashflowId:string;paid:IntString;status:string}>=[];for(const f of rows){const operationId=`settle:${f.cashflow_id}:${asOfDate}`;const old=op(branch,'cashflow',f.cashflow_id,operationId);if(old){out.push({cashflowId:f.cashflow_id,paid:old.amount,status:f.status});continue;}const cash=balance(branch,{ref:f.debtor_ref,currencyId:f.currency_id});const due=parseInteger(f.outstanding_amount,'outstanding');const paid=f.partial_allowed===1?(cash>0n?(cash<due?cash:due):0n):(cash>=due?due:0n);const remaining=due-paid;const status=remaining===0n?'paid':f.shortage_policy;let entry:LedgerEntryInput|null=null;if(paid>0n){entry={effectId:operationId,entryIndex:0,cause:'pagamento',kind:'money',unitId:f.currency_id,fromRef:f.debtor_ref,toRef:f.creditor_ref,delta:intToString(paid),atDate:asOfDate};appendLedgerEntries(game,branch,[entry]);}db.prepare('UPDATE finance_cashflows SET outstanding_amount=?,status=? WHERE branch_id=? AND cashflow_id=?').run(intToString(remaining),status,branch,f.cashflow_id);record(branch,'cashflow',f.cashflow_id,operationId,'settle',intToString(paid),null,entry,null);out.push({cashflowId:f.cashflow_id,paid:intToString(paid),status});}return out;});}
