/** M06 µ5c — staging server-side di effetti strict materiali. */
import db,{withCanonicalTransaction} from '../database';import {LedgerEntryInput,validateLedgerEntry} from '../domain/ledger';import {appendLedgerEntries} from './ledger.repository';
export class StrictEffectStagingError extends Error{readonly code:string;constructor(code:string,message:string){super(message);this.name='StrictEffectStagingError';this.code=code;}}
type Row={game_id:string;branch_id:string;anchor_revision:number;effect_id:string;kind:string;payload_json:string;status:string};
/** Fencing completo: partita esistente, ramo head di quella partita, revisione corrente. */
export function assertCanonicalEffectAnchor(gameId:string,branchId:string,anchorRevision:number):void{const row=db.prepare(`SELECT g.head_branch_id,g.world_revision,b.game_id AS branch_game_id FROM games g LEFT JOIN game_branches b ON b.id=? WHERE g.id=?`).get(branchId,gameId) as {head_branch_id:string|null;world_revision:number;branch_game_id:string|null}|undefined;if(!row||row.branch_game_id!==gameId||row.head_branch_id!==branchId)throw new StrictEffectStagingError('BAD_BRANCH_FENCE','ramo non head o non appartenente alla partita');if(row.world_revision!==anchorRevision)throw new StrictEffectStagingError('STALE_STAGED_EFFECT','anchor revision non corrente');}
function decodeEntry(value:unknown):LedgerEntryInput{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('payload non oggetto');const entry=value as LedgerEntryInput;validateLedgerEntry(entry);return entry;}function decodeOne(payload:string):LedgerEntryInput{try{return decodeEntry(JSON.parse(payload) as unknown);}catch(error){throw new StrictEffectStagingError('BAD_STAGED_PAYLOAD',error instanceof Error?error.message:'payload staged non valido');}}function decodeMany(payload:string):LedgerEntryInput[]{try{const raw:unknown=JSON.parse(payload);if(!Array.isArray(raw)||raw.length===0)throw new Error('lotto shipment non valido');return raw.map(decodeEntry);}catch(error){throw new StrictEffectStagingError('BAD_STAGED_PAYLOAD',error instanceof Error?error.message:'payload staged non valido');}}
function stage(gameId:string,branchId:string,anchorRevision:number,effectId:string,kind:'ledger'|'shipment',payload:string):boolean{if(!Number.isInteger(anchorRevision)||anchorRevision<0)throw new StrictEffectStagingError('BAD_ANCHOR','anchor revision non valida');return withCanonicalTransaction(()=>{assertCanonicalEffectAnchor(gameId,branchId,anchorRevision);const old=db.prepare('SELECT * FROM strict_effect_staging WHERE branch_id=? AND effect_id=?').get(branchId,effectId) as Row|undefined;if(old){if(old.kind!==kind||old.game_id!==gameId||old.anchor_revision!==anchorRevision||old.payload_json!==payload)throw new StrictEffectStagingError('STAGING_CONFLICT','effect staged già presente con contenuto o ancora diversa');return false;}db.prepare('INSERT INTO strict_effect_staging (game_id,branch_id,anchor_revision,effect_id,kind,payload_json) VALUES (?,?,?,?,?,?)').run(gameId,branchId,anchorRevision,effectId,kind,payload);return true;});}
function consume(gameId:string,branchId:string,anchorRevision:number,effectId:string,kind:'ledger'|'shipment',decode:(payload:string)=>LedgerEntryInput[]):boolean{return withCanonicalTransaction(()=>{assertCanonicalEffectAnchor(gameId,branchId,anchorRevision);const row=db.prepare('SELECT * FROM strict_effect_staging WHERE branch_id=? AND effect_id=?').get(branchId,effectId) as Row|undefined;if(!row)throw new StrictEffectStagingError('MISSING_STAGED_EFFECT','effectId non staged dal server');if(row.game_id!==gameId||row.kind!==kind||row.anchor_revision!==anchorRevision)throw new StrictEffectStagingError('STALE_STAGED_EFFECT','effect staged non appartiene all ancora canonica');if(row.status==='consumed')return false;if(row.status!=='staged')throw new StrictEffectStagingError('BAD_STAGED_STATUS','status staging non valido');const claimed=db.prepare("UPDATE strict_effect_staging SET status='consumed', consumed_at=CURRENT_TIMESTAMP WHERE branch_id=? AND effect_id=? AND status='staged'").run(branchId,effectId);if(claimed.changes!==1)throw new StrictEffectStagingError('STAGING_RACE','effect staging già consumato');appendLedgerEntries(gameId,branchId,decode(row.payload_json));return true;});}
/** Promozione consentita solo al checkpoint dello stesso ramo già avanzato da from a to. */
export function promoteStagedEffectAnchors(gameId:string,branchId:string,fromRevision:number,toRevision:number,effectIds:readonly string[]):number{if(!Number.isInteger(fromRevision)||fromRevision<0||toRevision!==fromRevision+1)throw new StrictEffectStagingError('BAD_PROMOTION','promozione anchor consentita solo al checkpoint consecutivo');return withCanonicalTransaction(()=>{assertCanonicalEffectAnchor(gameId,branchId,toRevision);let promoted=0;for(const effectId of new Set(effectIds)){const result=db.prepare("UPDATE strict_effect_staging SET anchor_revision=? WHERE game_id=? AND branch_id=? AND effect_id=? AND anchor_revision=? AND status='staged'").run(toRevision,gameId,branchId,effectId,fromRevision);promoted+=result.changes;}return promoted;});}

/** Solo un motore server usa questa API: retry identico è no-op, altro contenuto conflitto. */
export function stageLedgerEffect(gameId:string,branchId:string,anchorRevision:number,entry:LedgerEntryInput):boolean{validateLedgerEntry(entry);return stage(gameId,branchId,anchorRevision,entry.effectId,'ledger',JSON.stringify(entry));}
export function consumeStagedLedgerEffect(gameId:string,branchId:string,anchorRevision:number,effectId:string):boolean{return consume(gameId,branchId,anchorRevision,effectId,'ledger',x=>[decodeOne(x)]);}
/** Shipment deriva dal TransitEngine: solo movimenti fisici partenza/consegna/perdita. */
export function stageShipmentEffect(gameId:string,branchId:string,anchorRevision:number,effectId:string,entries:readonly LedgerEntryInput[]):boolean{if(entries.length===0)throw new StrictEffectStagingError('EMPTY_SHIPMENT','shipment senza movimenti');const indexes=new Set<number>();for(const entry of entries){validateLedgerEntry(entry);if(entry.kind!=='material'||!['partenza','consegna','perdita'].includes(entry.cause)||entry.effectId!==effectId||indexes.has(entry.entryIndex))throw new StrictEffectStagingError('BAD_SHIPMENT_PAYLOAD','movimento shipment non canonico');indexes.add(entry.entryIndex);}return stage(gameId,branchId,anchorRevision,effectId,'shipment',JSON.stringify(entries));}
export function consumeStagedShipmentEffect(gameId:string,branchId:string,anchorRevision:number,effectId:string):boolean{return consume(gameId,branchId,anchorRevision,effectId,'shipment',decodeMany);}
