/** M04 µ1 — ricetta esecutiva e calcolo fisico deterministico (§6.3). */
import { IntString,intToString,isIdString,parseInteger } from '../../domain/quantities';
export interface ResourceAmount { readonly resourceId:string; readonly baseUnits:IntString; }
export interface ExecutionRecipe { readonly id:string; readonly durationDays:number; readonly inputs:readonly ResourceAmount[]; readonly outputs:readonly ResourceAmount[]; readonly energy:{readonly resourceId:string;readonly baseUnitsPerUnit:IntString}; readonly labour:{readonly qualification:string;readonly minutesPerUnit:IntString}; readonly capacity:{readonly unitsPerDay:IntString}; }
export interface ProductionAvailability { readonly resources:Readonly<Record<string,IntString>>; readonly energy:Readonly<Record<string,IntString>>; readonly labourMinutes:Readonly<Record<string,IntString>>; }
export interface ProductionResult { readonly units:IntString; readonly consumed:readonly ResourceAmount[]; readonly produced:readonly ResourceAmount[]; readonly energyConsumed:ResourceAmount; readonly labourMinutes:IntString; readonly blockers:readonly ('MATERIAL_SHORTAGE'|'ENERGY_SHORTAGE'|'WORKFORCE_SHORTAGE'|'CAPACITY_LIMIT')[]; }
export class ProductionSchemaError extends Error { constructor(message:string){super(message);this.name='ProductionSchemaError';} }
function positive(v:IntString,label:string):bigint{const n=parseInteger(v,label);if(n<=0n)throw new ProductionSchemaError(`${label} deve essere > 0`);return n;}
function nonNegative(v:IntString,label:string):bigint{const n=parseInteger(v,label);if(n<0n)throw new ProductionSchemaError(`${label} deve essere >= 0`);return n;}
export function validateExecutionRecipe(r:ExecutionRecipe):void{if(!isIdString(r.id)||!Number.isInteger(r.durationDays)||r.durationDays<1)throw new ProductionSchemaError('id/durationDays non validi');if(!r.inputs.length||!r.outputs.length)throw new ProductionSchemaError('ricetta richiede input e output espliciti');for(const x of [...r.inputs,...r.outputs]){if(!isIdString(x.resourceId))throw new ProductionSchemaError('resourceId non valido');positive(x.baseUnits,'resource baseUnits');}if(!isIdString(r.energy.resourceId)||!isIdString(r.labour.qualification))throw new ProductionSchemaError('energia/lavoro devono essere espliciti');nonNegative(r.energy.baseUnitsPerUnit,'energy');positive(r.labour.minutesPerUnit,'labour');positive(r.capacity.unitsPerDay,'capacity');}
function available(map:Readonly<Record<string,IntString>>,id:string):bigint{return parseInteger(map[id]??'0',`availability.${id}`);}
/** Calcolo di UN giorno: il minimo dei vincoli, consumi proporzionali all'output effettivo. */
export function planDailyProduction(recipe:ExecutionRecipe,requestedUnits:IntString,availability:ProductionAvailability):ProductionResult{validateExecutionRecipe(recipe);let units=positive(requestedUnits,'requestedUnits');const blockers=new Set<ProductionResult['blockers'][number]>();const cap=positive(recipe.capacity.unitsPerDay,'capacity');if(units>cap){units=cap;blockers.add('CAPACITY_LIMIT');}for(const input of recipe.inputs){const max=available(availability.resources,input.resourceId)/positive(input.baseUnits,'input');if(max<units){units=max;blockers.add('MATERIAL_SHORTAGE');}}const energyPer=nonNegative(recipe.energy.baseUnitsPerUnit,'energy');if(energyPer>0n){const max=available(availability.energy,recipe.energy.resourceId)/energyPer;if(max<units){units=max;blockers.add('ENERGY_SHORTAGE');}}const labourPer=positive(recipe.labour.minutesPerUnit,'labour');const labour=available(availability.labourMinutes,recipe.labour.qualification)/labourPer;if(labour<units){units=labour;blockers.add('WORKFORCE_SHORTAGE');}const consumed=recipe.inputs.map(x=>({resourceId:x.resourceId,baseUnits:intToString(positive(x.baseUnits,'input')*units)}));const produced=recipe.outputs.map(x=>({resourceId:x.resourceId,baseUnits:intToString(positive(x.baseUnits,'output')*units)}));return{units:intToString(units),consumed,produced,energyConsumed:{resourceId:recipe.energy.resourceId,baseUnits:intToString(energyPer*units)},labourMinutes:intToString(labourPer*units),blockers:[...blockers]};}
