/** M04 µ2 — stato di lavoro e confini temporali (§6.3, §7.1). */
import { IntString,intToString,parseInteger } from '../../domain/quantities';
import { ExecutionRecipe,ProductionAvailability,ProductionResult,planDailyProduction } from './ProductionEngine';
export interface PendingOutput { readonly availableOn:string; readonly outputs:readonly {readonly resourceId:string;readonly baseUnits:IntString}[]; }
export interface WorkState { readonly completedUnits:IntString; readonly totalUnits:IntString; readonly pending:readonly PendingOutput[]; }
export interface ExtractionState extends WorkState { readonly depositId:string; readonly resourceId:string; readonly remainingDeposit:IntString; }
export interface TickResult<T> { readonly state:T; readonly production:ProductionResult; readonly workDate:string; readonly outputAvailableOn:string; }
function dayAfter(date:string):string{const d=new Date(`${date}T00:00:00.000Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10);}
function limit(recipe:ExecutionRecipe,state:WorkState,availability:ProductionAvailability):ProductionResult{const remaining=parseInteger(state.totalUnits,'total')-parseInteger(state.completedUnits,'completed');if(remaining<=0n)return planDailyProduction(recipe,'1',{resources:Object.fromEntries(recipe.inputs.map(x=>[x.resourceId,'0'])),energy:{[recipe.energy.resourceId]:'0'},labourMinutes:{[recipe.labour.qualification]:'0'}});return planDailyProduction(recipe,intToString(remaining),availability);}
/** Lavoro del giorno D: consumi subito, output solo da D+1. */
export function tickWorkDay(state:WorkState,recipe:ExecutionRecipe,date:string,availability:ProductionAvailability):TickResult<WorkState>{const production=limit(recipe,state,availability);const units=parseInteger(production.units,'units');const next:{completedUnits:IntString;totalUnits:IntString;pending:PendingOutput[]}={completedUnits:intToString(parseInteger(state.completedUnits,'completed')+units),totalUnits:state.totalUnits,pending:[...state.pending]};if(units>0n)next.pending.push({availableOn:dayAfter(date),outputs:production.produced});return{state:next,production,workDate:date,outputAvailableOn:dayAfter(date)};}
/** Rilascia solo output maturato al confine; il chiamante lo registra nello stock/ledger. */
export function releaseOutputs(state:WorkState,date:string):{state:WorkState;released:readonly {readonly resourceId:string;readonly baseUnits:IntString}[]}{const released: {resourceId:string;baseUnits:IntString}[]=[];const pending:PendingOutput[]=[];for(const p of state.pending){if(p.availableOn<=date)released.push(...p.outputs);else pending.push(p);}return{state:{...state,pending},released};}
/** Estrazione: un solo output coincidente col deposito; niente stock senza unità di lavoro. */
export function tickExtractionDay(state:ExtractionState,recipe:ExecutionRecipe,date:string,availability:ProductionAvailability):TickResult<ExtractionState>{if(recipe.outputs.length!==1||recipe.outputs[0]?.resourceId!==state.resourceId)throw new Error('extraction recipe incompatibile');const perUnit=parseInteger(recipe.outputs[0].baseUnits,'output');const deposit=parseInteger(state.remainingDeposit,'deposit');const capped:WorkState={...state,totalUnits:intToString((parseInteger(state.totalUnits,'total')-parseInteger(state.completedUnits,'completed'))<deposit/perUnit?parseInteger(state.totalUnits,'total'):parseInteger(state.completedUnits,'completed')+deposit/perUnit)};const tick=tickWorkDay(capped,recipe,date,availability);const extracted=parseInteger(tick.production.produced[0]?.baseUnits??'0','extracted');return{...tick,state:{...tick.state,depositId:state.depositId,resourceId:state.resourceId,remainingDeposit:intToString(deposit-extracted)}};}
