/** M03 µ3 — allocatore batch temporaneo (§5.3.10), nessuna mutazione. */
import { IntString,intToString,parseInteger } from '../../domain/quantities';
import { OrderIntent } from './intent';
export interface BatchDemand { readonly funds?:{readonly currencyId:string;readonly minorUnits:IntString}; readonly materials?:readonly {readonly resourceId:string;readonly baseUnits:IntString}[]; readonly workforce?:readonly {readonly qualification:string;readonly persons:IntString}[]; }
export interface BatchOrder { readonly intent:OrderIntent; readonly queueSequence:number; readonly demand:BatchDemand; }
export interface BatchPools { readonly funds:Readonly<Record<string,IntString>>; readonly materials:Readonly<Record<string,IntString>>; readonly workforce:Readonly<Record<string,IntString>>; }
export interface BatchBlocker { readonly code:'INSUFFICIENT_CASH'|'MATERIAL_SHORTAGE'|'WORKFORCE_SHORTAGE'|'DEPENDENCY_BLOCKED'; readonly id:string; readonly required:IntString; readonly available:IntString; }
export interface BatchResult { readonly actionId:string; readonly status:'feasible'|'blocked'; readonly blockers:readonly BatchBlocker[]; }
function val(x:IntString|undefined){return parseInteger(x??'0','pool');}
export function allocateBatch(orders:readonly BatchOrder[],pools:BatchPools):readonly BatchResult[]{const byId=new Map(orders.map(x=>[x.intent.id,x]));const sorted=[...orders].sort((a,b)=>a.intent.priority-b.intent.priority||a.queueSequence-b.queueSequence);const funds=new Map(Object.entries(pools.funds).map(([k,v])=>[k,val(v)]));const materials=new Map(Object.entries(pools.materials).map(([k,v])=>[k,val(v)]));const workforce=new Map(Object.entries(pools.workforce).map(([k,v])=>[k,val(v)]));const results=new Map<string,BatchResult>();const visiting=new Set<string>();
 const assess=(order:BatchOrder):BatchResult=>{const prior=results.get(order.intent.id);if(prior)return prior;if(visiting.has(order.intent.id)){const r:{actionId:string;status:'blocked';blockers:BatchBlocker[]}={actionId:order.intent.id,status:'blocked',blockers:[{code:'DEPENDENCY_BLOCKED',id:order.intent.id,required:'1',available:'0'}]};results.set(order.intent.id,r);return r;}visiting.add(order.intent.id);for(const depId of order.intent.dependencyIds){const dep=byId.get(depId);const dr=dep?assess(dep):undefined;if(!dr||dr.status==='blocked'){const r={actionId:order.intent.id,status:'blocked' as const,blockers:[{code:'DEPENDENCY_BLOCKED' as const,id:depId,required:'1',available:'0'}]};results.set(order.intent.id,r);visiting.delete(order.intent.id);return r;}}
 const blockers:BatchBlocker[]=[];const f=order.demand.funds;if(f){const available=funds.get(f.currencyId)??0n;const required=val(f.minorUnits);if(required>available)blockers.push({code:'INSUFFICIENT_CASH',id:f.currencyId,required:f.minorUnits,available:intToString(available)});}for(const m of order.demand.materials??[]){const available=materials.get(m.resourceId)??0n;if(val(m.baseUnits)>available)blockers.push({code:'MATERIAL_SHORTAGE',id:m.resourceId,required:m.baseUnits,available:intToString(available)});}for(const w of order.demand.workforce??[]){const available=workforce.get(w.qualification)??0n;if(val(w.persons)>available)blockers.push({code:'WORKFORCE_SHORTAGE',id:w.qualification,required:w.persons,available:intToString(available)});}const r:BatchResult=blockers.length?{actionId:order.intent.id,status:'blocked',blockers}:{actionId:order.intent.id,status:'feasible',blockers:[]};if(!blockers.length){if(f)funds.set(f.currencyId,(funds.get(f.currencyId)??0n)-val(f.minorUnits));for(const m of order.demand.materials??[])materials.set(m.resourceId,(materials.get(m.resourceId)??0n)-val(m.baseUnits));for(const w of order.demand.workforce??[])workforce.set(w.qualification,(workforce.get(w.qualification)??0n)-val(w.persons));}results.set(order.intent.id,r);visiting.delete(order.intent.id);return r;};for(const order of sorted)assess(order);return orders.map(x=>results.get(x.intent.id)??{actionId:x.intent.id,status:'blocked',blockers:[]});}
