/** M03 µ2 — gate puro §5.3: nessuna riserva, I/O o LLM. */
import { SimulationCatalog, AuthorityRule } from '../../scenario/types';
import { OrderIntent } from './intent';
export type AssessmentStatus='needs_data'|'blocked'|'feasible'|'feasible_with_conditions';
export type ReasonCode='UNKNOWN_ENTITY'|'AMBIGUOUS_TARGET'|'UNAUTHORIZED_ACTOR'|'UNSUPPORTED_CAPABILITY'|'KNOWLEDGE_MISSING'|'INDUSTRIAL_CAPABILITY_MISSING'|'DATA_UNAVAILABLE'|'DEPENDENCY_BLOCKED';
export interface Blocker{readonly code:ReasonCode;readonly targetId?:string;readonly detail:string;readonly missing?:readonly string[];}
export interface Requirement{readonly allOf?:readonly string[];readonly anyOf?:readonly (readonly string[])[];}
export interface FeasibilityFacts{readonly actorId:string;readonly verifiedPolityId:string;readonly approvals:readonly ('user'|'institutional'|'counterparty')[];readonly rights:readonly {readonly targetId:string;readonly activity:string}[];readonly knowledgeIds:readonly string[];readonly capabilityIds:readonly string[];readonly requirements?:Readonly<Record<string,Requirement>>;readonly modelDataMissingIds?:readonly string[];readonly hiddenFromPlayerIds?:readonly string[];}
export interface AlternativeProposal { readonly kind:'research'|'alternative_path'; readonly requiresConfirmation:true; readonly missing:readonly string[]; }
export interface OrderAssessment{readonly actionId:string;readonly status:AssessmentStatus;readonly blockers:readonly Blocker[];readonly warnings:readonly string[];readonly alternatives:readonly AlternativeProposal[];}
function hasAll(have:Set<string>,need:readonly string[]){return need.filter(x=>!have.has(x));}
/** Ogni alternativa è una via completa: allOf comune + almeno una anyOf, mai tutte le vie. */
export function satisfiesRequirement(have:ReadonlySet<string>, requirement:Requirement|undefined):{ok:boolean;missing:readonly string[]}{if(!requirement)return{ok:true,missing:[]};const base=hasAll(new Set(have),requirement.allOf??[]);if(base.length)return{ok:false,missing:base};const alternatives=requirement.anyOf??[];if(!alternatives.length)return{ok:true,missing:[]};for(const path of alternatives){const missing=hasAll(new Set(have),path);if(!missing.length)return{ok:true,missing:[]};}return{ok:false,missing:alternatives[0]??[]};}
function authorityActivity(intent:OrderIntent):string|null{return intent.actionKind==='procure'||intent.actionKind==='move'?'spend':intent.actionKind==='produce'||intent.actionKind==='construct'?'allocate':intent.actionKind==='policy'?'policy':null;}
function targetKnown(catalog:SimulationCatalog,id:string):boolean{return catalog.resources.some(x=>x.id===id)||catalog.recipes.some(x=>x.id===id)||catalog.technologies.some(x=>x.id===id)||catalog.facilityTypes.some(x=>x.id===id)||catalog.initialState.facilities.some(x=>x.id===id)||catalog.initialState.inventory.some(x=>x.id===id)||catalog.initialState.deposits.some(x=>x.id===id)||catalog.polities.some(x=>x.id===id);}
function actorRule(catalog:SimulationCatalog,actorId:string,activity:string):AuthorityRule|undefined{const actor=catalog.actors.find(x=>x.actorId===actorId);return actor?catalog.authorities.find(x=>x.actorType===actor.type&&x.activity===activity):undefined;}
export class FeasibilityService { constructor(private readonly catalog:SimulationCatalog) {}
 evaluate(intent:OrderIntent,facts:FeasibilityFacts):OrderAssessment {const blockers:Blocker[]=[];const warnings:string[]=[];const alternatives:AlternativeProposal[]=[];const missingData=new Set(facts.modelDataMissingIds??[]);const hidden=new Set(facts.hiddenFromPlayerIds??[]);if(intent.actorPolityId!==facts.verifiedPolityId)blockers.push({code:'UNAUTHORIZED_ACTOR',detail:'actorPolityId non coincide con identità verificata dal server'});const actor=this.catalog.actors.find(x=>x.actorId===facts.actorId);if(!actor||actor.polityId!==facts.verifiedPolityId)blockers.push({code:'UNAUTHORIZED_ACTOR',detail:'attore economico non autorizzato per polity verificata'});
 for(const target of intent.targetIds){if(missingData.has(target))blockers.push({code:'DATA_UNAVAILABLE',targetId:target,detail:'model_data_missing: nessun dato autorevole'});else if(hidden.has(target))blockers.push({code:'DATA_UNAVAILABLE',targetId:target,detail:'hidden_from_player: dato esiste ma non è rivelato'});else if(!targetKnown(this.catalog,target))blockers.push({code:'UNKNOWN_ENTITY',targetId:target,detail:'target assente dal catalogo'});}
 const activity=authorityActivity(intent);if(activity&&actor){const rule=actorRule(this.catalog,facts.actorId,activity);if(!rule)blockers.push({code:'UNAUTHORIZED_ACTOR',detail:`nessuna regola R1 per attività ${activity}`});else{const approved=new Set(facts.approvals);const absent=rule.requiresApprovals.filter(x=>!approved.has(x));if(absent.length)blockers.push({code:'UNAUTHORIZED_ACTOR',detail:`consensi mancanti: ${absent.join(',')}`});}}
 const requirement=facts.requirements?.[intent.catalogRef??intent.actionKind];const knowledge=satisfiesRequirement(new Set(facts.knowledgeIds),requirement);if(!knowledge.ok){blockers.push({code:'KNOWLEDGE_MISSING',detail:'prerequisiti di conoscenza non soddisfatti',missing:knowledge.missing});alternatives.push({kind:'research',requiresConfirmation:true,missing:knowledge.missing});if((requirement?.anyOf?.length??0)>1)alternatives.push({kind:'alternative_path',requiresConfirmation:true,missing:knowledge.missing});}
 if(intent.actionKind==='produce'){const recipe=this.catalog.recipes.find(x=>x.id===intent.catalogRef);const facility=this.catalog.initialState.facilities.find(x=>x.id===intent.targetIds[0]);if(!recipe||!facility){blockers.push({code:'UNKNOWN_ENTITY',detail:'ricetta o impianto assente'});}else if(!facility.operational||facility.typeId!==recipe.facilityTypeId){blockers.push({code:'INDUSTRIAL_CAPABILITY_MISSING',targetId:facility.id,detail:'impianto non operativo o incompatibile con ricetta'});}else if(facility.ownerActorId!==facts.actorId&&facility.controllerActorId!==facts.actorId&&!facts.rights.some(x=>x.targetId===facility.id&&x.activity==='operate')){blockers.push({code:'UNAUTHORIZED_ACTOR',targetId:facility.id,detail:'nessun diritto d uso dell impianto'});}}
 if(intent.actionKind==='move'||intent.actionKind==='procure'){const lot=this.catalog.initialState.inventory.find(x=>x.id===intent.targetIds[0]);if(lot&&lot.ownerActorId!==facts.actorId&&lot.custodianActorId!==facts.actorId&&!facts.rights.some(x=>x.targetId===lot.id&&x.activity==='use'))blockers.push({code:'UNAUTHORIZED_ACTOR',targetId:lot.id,detail:'stock privato/altrui senza diritto o contratto'});}
 if(intent.authorization.allowPartialStart&&intent.authorization.allowedPhaseIds.length===0)warnings.push('avvio parziale richiesto ma nessuna fase autorizzata: nessun avvio parziale verrà applicato');if(intent.actionKind==='qualitative')warnings.push('ordine qualitativo: nessuna ricetta o effetto materiale valutato');const status:AssessmentStatus=blockers.some(x=>x.code==='DATA_UNAVAILABLE')?'needs_data':blockers.length?'blocked':warnings.length?'feasible_with_conditions':'feasible';return{actionId:intent.id,status,blockers,warnings,alternatives};}
}
