/** M03 µ1 — normalizzazione deterministica OrderIntent (§5.2). */
import { IntString, isIdString, parseInteger } from '../../domain/quantities';

export const ACTION_KINDS = ['construct','produce','procure','research','train','maintain','move','policy','diplomatic_proposal','cancel_project','qualitative'] as const;
export type ActionKind = typeof ACTION_KINDS[number];
export interface AmountIntent { readonly currencyId:string; readonly minorUnits:IntString; }
export interface AuthorizationIntent { readonly maxCommitment?:AmountIntent; readonly allowPartialStart:boolean; readonly allowedPhaseIds:readonly string[]; readonly financingPolicyId?:string; readonly delegationMandateId?:string; }
export interface OrderIntent { readonly id:string; readonly actorPolityId:string; readonly originalText:string; readonly actionKind:ActionKind; readonly targetIds:readonly string[]; readonly catalogRef?:string; readonly quantity?:{readonly resourceId:string;readonly baseUnits:IntString}; readonly priority:number; readonly dependencyIds:readonly string[]; readonly authorization:AuthorizationIntent; }
export interface Clarification { readonly code:string; readonly field:string; readonly message:string; }
export type NormalizeIntentResult={readonly ok:true;readonly intent:OrderIntent}|{readonly ok:false;readonly status:'needs_clarification';readonly clarifications:readonly Clarification[]};
const ARITY:Record<ActionKind,number>={construct:2,produce:1,procure:3,research:1,train:2,maintain:1,move:2,policy:1,diplomatic_proposal:1,cancel_project:1,qualitative:0};
const NEEDS_CATALOG=new Set<ActionKind>(['construct','produce','research','train','maintain','policy']);
const NEEDS_QUANTITY=new Set<ActionKind>(['produce','procure','train','move']);
// ID d'ordine/catalogo (polity/region/facility) non sono ID unità: M01 usa
// es. ALPHA e ALPHA-nord. Valute/risorse restano validate dal codec minuscolo.
const INTENT_ID=/^[A-Za-z][A-Za-z0-9_:-]{0,127}$/;
function intentId(value:unknown):value is string{return typeof value==='string'&&INTENT_ID.test(value);}
function object(v:unknown):Record<string,unknown>|null{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:null;}
function add(out:Clarification[],code:string,field:string,message:string):void{out.push({code,field,message});}
function ids(v:unknown,field:string,out:Clarification[]):string[]{if(!Array.isArray(v)){add(out,'MISSING_FIELD',field,'campo obbligatorio');return [];}const result:string[]=[];for(const [i,x] of v.entries()){if(!intentId(x)){add(out,'INVALID_ID',`${field}[${i}]`,'atteso ID canonico');continue;}if(result.includes(x)){add(out,'DUPLICATE_ID',`${field}[${i}]`,'ID duplicato');continue;}result.push(x);}return result;}
export function normalizeOrderIntent(value:unknown):NormalizeIntentResult {const raw=object(value);const issues:Clarification[]=[];if(!raw){return{ok:false,status:'needs_clarification',clarifications:[{code:'INVALID_SCHEMA',field:'order',message:'atteso oggetto'}]};}
 const id=raw.id;if(!intentId(id))add(issues,'INVALID_ID','id','ID ordine obbligatorio');const actor=raw.actorPolityId;if(!intentId(actor))add(issues,'INVALID_ID','actorPolityId','polity obbligatoria (verifica server successiva)');const text=raw.originalText;if(typeof text!=='string'||!text.trim()||text.length>10000)add(issues,'MISSING_FIELD','originalText','testo originale obbligatorio');const kind=raw.actionKind;if(typeof kind!=='string'||!(ACTION_KINDS as readonly string[]).includes(kind)){add(issues,'UNKNOWN_ACTION_KIND','actionKind','azione non supportata: chiedere chiarimento, non inferire');}
 const actionKind=(typeof kind==='string'&&(ACTION_KINDS as readonly string[]).includes(kind)?kind:'qualitative') as ActionKind;const targets=ids(raw.targetIds,'targetIds',issues);if(targets.length!==ARITY[actionKind])add(issues,'AMBIGUOUS_TARGET','targetIds',`azione ${actionKind}: richiesti esattamente ${ARITY[actionKind]} target`);
 const catalogRef=raw.catalogRef;if(NEEDS_CATALOG.has(actionKind)&&!intentId(catalogRef))add(issues,'MISSING_CATALOG_REF','catalogRef',`azione ${actionKind}: catalogRef obbligatorio`);if(!NEEDS_CATALOG.has(actionKind)&&catalogRef!==undefined&&!intentId(catalogRef))add(issues,'INVALID_ID','catalogRef','catalogRef non canonico');
 let quantity:OrderIntent['quantity'];const q=object(raw.quantity);if(NEEDS_QUANTITY.has(actionKind)){if(!q||!isIdString(q.resourceId)||typeof q.baseUnits!=='string'){add(issues,'MISSING_QUANTITY','quantity','quantità/unità obbligatorie');}else{try{if(parseInteger(q.baseUnits,'quantity.baseUnits')<=0n)add(issues,'INVALID_QUANTITY','quantity.baseUnits','quantità deve essere > 0');else quantity={resourceId:q.resourceId,baseUnits:q.baseUnits};}catch{add(issues,'INVALID_QUANTITY','quantity.baseUnits','intero canonico obbligatorio');}}}else if(q){add(issues,'UNEXPECTED_MATERIAL_EFFECT','quantity','quantità non ammessa per questa azione');}
 if(actionKind==='qualitative'&&(raw.catalogRef!==undefined||raw.quantity!==undefined||targets.length>0))add(issues,'QUALITATIVE_MATERIAL_EFFECT','qualitative','ordine qualitativo non contiene target/catalogo/quantità materiali');
 const priority=raw.priority;if(!Number.isInteger(priority)||typeof priority!=='number'||priority<0||priority>1000000)add(issues,'INVALID_PRIORITY','priority','intero server-order 0..1000000 obbligatorio');const dependencies=ids(raw.dependencyIds,'dependencyIds',issues);if(typeof id==='string'&&dependencies.includes(id))add(issues,'DEPENDENCY_SELF','dependencyIds','un ordine non dipende da sé stesso');
 const auth=object(raw.authorization);let authorization:AuthorizationIntent|undefined;if(!auth){add(issues,'MISSING_AUTHORIZATION','authorization','autorizzazione esplicita obbligatoria');}else{const phases=ids(auth.allowedPhaseIds,'authorization.allowedPhaseIds',issues);if(typeof auth.allowPartialStart!=='boolean')add(issues,'MISSING_FIELD','authorization.allowPartialStart','boolean esplicito obbligatorio');let max:AmountIntent|undefined;if(auth.maxCommitment!==undefined){const m=object(auth.maxCommitment);if(!m||!isIdString(m.currencyId)||typeof m.minorUnits!=='string'){add(issues,'INVALID_AMOUNT','authorization.maxCommitment','valuta e unità minime canoniche obbligatorie');}else{try{if(parseInteger(m.minorUnits,'maxCommitment')<0n)add(issues,'INVALID_AMOUNT','authorization.maxCommitment.minorUnits','non negativo');else max={currencyId:m.currencyId,minorUnits:m.minorUnits};}catch{add(issues,'INVALID_AMOUNT','authorization.maxCommitment.minorUnits','intero canonico obbligatorio');}}}for(const key of ['financingPolicyId','delegationMandateId'] as const){if(auth[key]!==undefined&&!intentId(auth[key]))add(issues,'INVALID_ID',`authorization.${key}`,'ID canonico obbligatorio');}if(typeof auth.allowPartialStart==='boolean')authorization={allowPartialStart:auth.allowPartialStart,allowedPhaseIds:phases,maxCommitment:max,financingPolicyId:auth.financingPolicyId as string|undefined,delegationMandateId:auth.delegationMandateId as string|undefined};}
 if(issues.length>0||!authorization||!intentId(id)||!intentId(actor)||typeof text!=='string'||!text.trim()||typeof priority!=='number'||!Number.isInteger(priority))return{ok:false,status:'needs_clarification',clarifications:issues};return{ok:true,intent:{id,actorPolityId:actor,originalText:text,actionKind,targetIds:targets,catalogRef:intentId(catalogRef)?catalogRef:undefined,quantity,priority,dependencyIds:dependencies,authorization}}; }
